export { PostSkeleton } from './post/skeleton/Skeleton';
export { Post } from './post/Post';
export { Header } from './header/Header';
export { Index } from './addComment/AddComment';
export { UserInfo } from './userInfo/UserInfo';
export { SideBlock } from './sideBlock/SideBlock';
export { CommentsBlock } from './commentsBlock/CommentsBlock';
export { TagsBlock } from './tagsBlock/TagsBlock';
export { SimpleBackdrop } from './simpleBackdrop/SimpleBackdrop';
